export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_RESTER'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_ERRORS = 'GET_ERRORS'
